### ISSUE TITLE
Hey...!

### ISSUE THREAD

**Issue by Cramoisi-San** [lodni/ZeroCraftTerrariaMod#1]
So, i know that you didn't update this mod since a year+ ago, but... I wanted to know if it'd be possible if this mod either gets updated to 1.4, or if you could publish code source so that others can do it ?

**Comment by ekyo** [comment]
It's ready for publish but waiting on Item Checklist to be published first since it is a dependency.

Until then, you can probably make it work by extracting this into Documents\My Games\Terraria\tModLoader\Mods

[Mods.zip](https://github.com/lodni/ZeroCraftTerrariaMod/files/9622761/Mods.zip)

**Comment by ekyo** [comment]
Even better, it got published faster than I expected, mod is now updated and published~~
